- name: general-american
  displayName: "General American"
  sounds:
    - "R"
    - "L"
    - "AE"
- name: irish
  displayName: "Irish"
  sounds:
    - "AE"
    - "L"
    - "AH"
    - "DH"
    - "TH"
    - "EY"
    - "OW"
    - "OY"
    - "AY"
- name: rp
  displayName: "RP"
  sounds:
    - "L"
    - "R"
    - "OW"
- name: liverpool
  displayName: "Liverpool"
  sounds:
    - "R"
    - "L"
    - "EY"
    - "OW"
- name: cockney
  displayName: "Cockney"
  sounds:
    - "TH"
    - "DH"
    - "L"
    - "AY"
