- symbol: "L"
  name: "The L Sound"
- symbol: "R"
  name: "The R Sound"
- symbol: "S"
  name: "The S Sound"
- symbol: "F"
  name: "The F Sound"
- symbol: "K"
  name: "The K Sound"
- symbol: "TH"
  name: "The Unvoiced TH"
- symbol: "DH"
  name: "The Voiced TH"
- symbol: "V"
  name: "The V Sound"
