- symbol: "AA"
  name: "The Oh/Ah Sound"
- symbol: "AE"
  name: "The Wide 'Ah' Sound"
- symbol: "AH"
  name: "The Schwa"
- symbol: "AO"
  name: "The 'Or' Sound"
- symbol: "AW"
  name: "The 'Ow' Sound"
- symbol: "AY"
  name: "The 'I' Sound"
- symbol: "B"
  name: "The B Sound"
- symbol: "CH"
  name: "The Ch Sound"
- symbol: "D"
  name: "The D Sound"
- symbol: "DH"
  name: "The Voiced TH"
- symbol: "EH"
  name: "The 'Eh' Sound"
- symbol: "ER"
  name: "The 'Ur' Sound"
- symbol: "EY"
  name: "The 'Ey' Sound"
- symbol: "F"
  name: "The F Sound"
- symbol: "G"
  name: "The Hard 'G'"
- symbol: "HH"
  name: "The H Sound"
- symbol: "IH"
  name: "The 'Ih' Sound"
- symbol: "IY"
  name: "The 'Ee' Sound"
- symbol: "JH"
  name: "The J Sound"
- symbol: "K"
  name: "The K Sound"
- symbol: "L"
  name: "The L Sound"
- symbol: "M"
  name: "The M Sound"
- symbol: "N"
  name: "The N Sound"
- symbol: "NG"
  name: "The NG Sound"
- symbol: "OW"
  name: "The 'O' Sound"
- symbol: "OY"
  name: "The 'Oy' Sound"
- symbol: "P"
  name: "The P Sound"
- symbol: "R"
  name: "The R Sound"
- symbol: "S"
  name: "The S Sound"
- symbol: "SH"
  name: "The SH Sound"
- symbol: "T"
  name: "The T Sound"
- symbol: "TH"
  name: "The Unvoiced TH"
- symbol: "UH"
  name: "The Short 'Oo'"
- symbol: "UW"
  name: "The Long 'Oo'"
- symbol: "V"
  name: "The V Sound"
- symbol: "W"
  name: "The W Sound"
- symbol: "Y"
  name: "The Y Sound"
- symbol: "Z"
  name: "The Z Sound"
- symbol: "ZH"
  name: "The 'Zh' Sound"
